### ISSUE TITLE
Manque de transceivers sur le nord et la Bretagne pour LFFM_CTR

### ISSUE THREAD

**Issue by rmaure06** [vaccfr/France-Ground-Layouts#106]
Carte des transceivers actuels: 
![image](https://user-images.githubusercontent.com/64205205/168983251-3fd95fce-1c8e-48f0-af8d-904cf9a5075b.png)

**Comment by Pampah91** [comment]
![Capture](https://github.com/user-attachments/assets/9ed18431-4710-4674-989c-f0ab887ed62c)
J'ai rajouté depuis des transceivers sur Brest et également ailleurs. Ils sont tous centrés sur les bases La photo représente la portée en surface, le territoire est complètement couvert en passant le FL60.

Les dernières sessions en 2024 semblent concluantes.

**Comment by herver** [comment]
Je passe l'issue en "résolu".
N'hésite pas à la réouvrir si ça ne marche pas
