### ISSUE TITLE
[Ajout secteur] LFLC

### ISSUE THREAD

**Issue by rmaure06** [vaccfr/France-Ground-Layouts#108]
Plateforme: LFLC
Pull request associé: #109 

Changelog: 
- Nouvel AVISO complet

Fichiers format GNG:
[LFLC Regions.txt](https://github.com/vaccfr/France-Ground-Layouts/files/9931114/LFLC.Regions.txt)
[LFLC Geo.txt](https://github.com/vaccfr/France-Ground-Layouts/files/9931115/LFLC.Geo.txt)
[LFLC Labels.txt](https://github.com/vaccfr/France-Ground-Layouts/files/9931116/LFLC.Labels.txt)

Fichiers format SCT:
[LFLC SCT - Maj.txt](https://github.com/vaccfr/France-Ground-Layouts/files/9931124/LFLC.SCT.-.Maj.txt)
[LFLC ESE - Maj.txt](https://github.com/vaccfr/France-Ground-Layouts/files/9931125/LFLC.ESE.-.Maj.txt)

**Comment by rmaure06** [comment]
Uploaded on GNG

**Comment by herver** [comment]
Thanks, SCT and ESE will be added soon here as part of the revamp of the repo
