### ISSUE TITLE
LFPG -  BD10 can be used forward to join A.

### ISSUE THREAD

**Issue by fx182ch** [vaccfr/France-Ground-Layouts#27]
![image](https://user-images.githubusercontent.com/3285637/117665740-72476800-b1a3-11eb-89c0-0152d78f0d2c.png)

**Comment by fx182ch** [comment]
An example of what should be done.

![image](https://user-images.githubusercontent.com/3285637/117666300-ff8abc80-b1a3-11eb-94c4-c23a2cb99c85.png)

**Comment by rmaure06** [comment]
Done and merged in #64 - Issue can be closed
