### ISSUE TITLE
[Ajout secteur] LFPO

### ISSUE THREAD

**Issue by rmaure06** [vaccfr/France-Ground-Layouts#32]
Plateforme: LFPO
Pull request associé: #31 

Changelog:
- Complete redraw from scratch
- Major gates drawn as paths
- Added holding points as regions
- Updated taxiways and parkings
- Freetext overall redone to match new polygons

Fichers:
[LFPO SCT - Maj.txt](https://github.com/vaccfr/France-Ground-Layouts/files/7138306/LFPO.Orly.v2.-.SCT.txt)
[LFPO ESE - Maj.txt](https://github.com/vaccfr/France-Ground-Layouts/files/7138307/LFPO.Orly.v2.-.ESE.txt)

**Comment by pierr3** [comment]
Implemented in AIRAC  2109/01
