### ISSUE TITLE
[Ajout secteur] LFMN

### ISSUE THREAD

**Issue by rmaure06** [vaccfr/France-Ground-Layouts#33]
Plateforme: LFMN
Pull request associé: [to be defined]

Changelog:
- Complete redraw from scratch

Fichers:
[LFMN SCT - Maj.txt](https://github.com/vaccfr/France-Ground-Layouts/files/7138325/LFMN.Nice.v2.-.SCT.txt)
[LFMN ESE - Maj.txt](https://github.com/vaccfr/France-Ground-Layouts/files/7138326/LFMN.Nice.v2.-.ESE.txt)

**Comment by pierr3** [comment]
Implemented in AIRAC 2109/01
