### ISSUE TITLE
[Ajout secteur] LFPB

### ISSUE THREAD

**Issue by rmaure06** [vaccfr/France-Ground-Layouts#34]
Plateforme: LFPB
Pull request associé: [to be defined]

Changelog: 
- Complete redrawn from scratch (thanks to Mohamed B.)
- Complete new freetext to match new polygons

Fichers:
[LFPB SCT - Maj.txt](https://github.com/vaccfr/France-Ground-Layouts/files/7138340/LFPB.AVISO.v2.-.SCT.txt)
[LFPB ESE - Maj.txt](https://github.com/vaccfr/France-Ground-Layouts/files/7138343/LFPB.AVISO.v2.-.ESE.txt)

**Comment by pierr3** [comment]
Implemented in AIRAC 2109/01
