### ISSUE TITLE
[Ajout secteur] LFMT

### ISSUE THREAD

**Issue by rmaure06** [vaccfr/France-Ground-Layouts#35]
Plateforme: LFMT
Pull request associé: [to be define]

Changelog: 
- Complete draw from scratch (by Thilo C.)

Fichers:
[LFMT SCT - Maj.txt](https://github.com/vaccfr/France-Ground-Layouts/files/7138358/LFMT_AVISO.1.txt)
[LFMT ESE - Maj.txt](https://github.com/vaccfr/France-Ground-Layouts/files/7138360/LFMT_FREETEXT.txt)

**Comment by pierr3** [comment]
Implemented in AIRAC 2109/01
