### ISSUE TITLE
[Ajout secteur] LFST

### ISSUE THREAD

**Issue by rmaure06** [vaccfr/France-Ground-Layouts#36]
Plateforme: LFST
Pull request associé: [to be defined]

Changelog:
- Complete draw from scratch (by Thilo C.)
- Complete new freetext to match new polygons (by Thilo C.)

Fichers:
[LFST SCT - Maj.txt](https://github.com/vaccfr/France-Ground-Layouts/files/7138382/LFST.SCT.-.Maj.txt)
[LFST ESE - Maj.txt](https://github.com/vaccfr/France-Ground-Layouts/files/7138383/LFST.ESE.-.Maj.txt)

**Comment by pierr3** [comment]
Implemented in AIRAC 2109/01
