### ISSUE TITLE
[Ajout secteur] LFBZ

### ISSUE THREAD

**Issue by rmaure06** [vaccfr/France-Ground-Layouts#37]
Plateforme: LFBZ
Pull request associé: [to be defined]

Changelog: 
- Complete new drawn from scratch (by Thilo C.)
- Complete new freetext to match new polygons ( by Thilo C.)

Fichers:
[LFBZ SCT - Maj.txt](https://github.com/vaccfr/France-Ground-Layouts/files/7138400/LFBZ.SCT.-.Maj.txt)
[LFBZ ESE - Maj.txt](https://github.com/vaccfr/France-Ground-Layouts/files/7138401/LFBZ.ESE.-.Maj.txt)

**Comment by pierr3** [comment]
Implemented with AIRAC 2109/01
