### ISSUE TITLE
LFPG - Draw intermediate Holding point for Apron

### ISSUE THREAD

**Issue by fx182ch** [vaccfr/France-Ground-Layouts#4]
Draw them as region instead of line.

**Comment by rmaure06** [comment]
Done in #26

**Comment by fx182ch** [comment]
> Done in #26

No I was talking about TA1, TB1, etc..
![image](https://user-images.githubusercontent.com/3285637/133000027-e8d5a240-6d61-44d7-bd20-e710f5f378d1.png)
![image](https://user-images.githubusercontent.com/3285637/133000059-c7407d54-07c3-4974-85bc-03f72177c658.png)

The goal here is to have visual marker for when we split GND and Apron.

**Comment by rmaure06** [comment]
After double checking, it has indeed been implemented in #26 (AIRAC 2109/01)

**Comment by fx182ch** [comment]
Indeed it's in the sector file:
![image](https://user-images.githubusercontent.com/3285637/133002377-13db9474-9866-4acf-af87-6709ed898233.png)

Before closing the issue could we just check that it's implemented into the KML/KMZ for LFPG ?
