### ISSUE TITLE
[Ajout secteur] LFKJ

### ISSUE THREAD

**Issue by rmaure06** [vaccfr/France-Ground-Layouts#51]
Plateforme: LFKJ
Pull request associé: #50 
Changelog: 
- New AVISO drawn from scratch

Fichiers:
[LFKJ SCT - Maj.txt](https://github.com/vaccfr/France-Ground-Layouts/files/7149972/LFKJ.SCT.-.Maj.txt)
[LFKJ ESE - Maj.txt](https://github.com/vaccfr/France-Ground-Layouts/files/7149973/LFKJ.ESE.-.Maj.txt)

**Comment by rmaure06** [comment]
Fichiers format GNG:
[LFKJ Regions.txt](https://github.com/vaccfr/France-Ground-Layouts/files/7149975/LFKJ.Regions.txt)
[LFKJ Geo.txt](https://github.com/vaccfr/France-Ground-Layouts/files/7149976/LFKJ.Geo.txt)
[LFKJ Labels.txt](https://github.com/vaccfr/France-Ground-Layouts/files/7149977/LFKJ.Labels.txt)

**Comment by pierr3** [comment]
Implemented in November AIRAC
