### ISSUE TITLE
[Ajout secteur] LFMT Geo

### ISSUE THREAD

**Issue by rmaure06** [vaccfr/France-Ground-Layouts#52]
Plateforme: LFMT
Pull request associé: #48 

Partie [GEO] manquante sur l'AVISO de LFMT - à ajouter en tant que **LFMT AVISO Geo** (au lieu de LFMT Groundlayout Montpellier) afin d'éviter la confusion avec l'ancien dessin.

Fichier format GNG:
[LFMT GEO.txt](https://github.com/vaccfr/France-Ground-Layouts/files/7149979/LFMT.GEO.txt)

**Comment by pierr3** [comment]
Implemented in november airac
