### ISSUE TITLE
[Ajout secteur] LFBZ Geo

### ISSUE THREAD

**Issue by rmaure06** [vaccfr/France-Ground-Layouts#53]
Plateforme: LFBZ
Pull request associé: #47 

Partie [GEO] manquante sur LFBZ - à ajouter en tant que **LFBZ AVISO Geo** (au lieu de LFBZ Groundlayout Biarritz) afin d'éviter la confusion avec l'ancien dessin.

Fichier format GNG:
[LFBZ GEO.txt](https://github.com/vaccfr/France-Ground-Layouts/files/7149981/LFBZ.GEO.txt)

**Comment by pierr3** [comment]
Implemented in November AIRAC
