### ISSUE TITLE
[Ajout secteur] LFST Geo

### ISSUE THREAD

**Issue by rmaure06** [vaccfr/France-Ground-Layouts#54]
Plateforme: LFST
Pull request associé: #49   

Partie [GEO] manquante sur LFST - à ajouter en tant que **LFST AVISO Geo** (au lieu de LFST Groundlayout Strasbourg) afin d'éviter la confusion avec l'ancien dessin.

Fichier format GNG:
[LFST GEO.txt](https://github.com/vaccfr/France-Ground-Layouts/files/7149988/LFST.GEO.txt)

**Comment by pierr3** [comment]
Implemented in November AIRAC
