### ISSUE TITLE
[Ajout secteur] LFOB

### ISSUE THREAD

**Issue by rmaure06** [vaccfr/France-Ground-Layouts#60]
Plateforme: LFOB
Pull request associé: #59 

Changelog: 
- Redessin complet d'un AVISO

Fichiers format Euroscope:
[LFOB SCT - Maj.txt](https://github.com/vaccfr/France-Ground-Layouts/files/7163883/LFOB.SCT.-.Maj.txt)
[LFOB ESE - Maj.txt](https://github.com/vaccfr/France-Ground-Layouts/files/7163884/LFOB.ESE.-.Maj.txt)

Fichiers format GNG:
[LFOB Regions.txt](https://github.com/vaccfr/France-Ground-Layouts/files/7163886/LFOB.Regions.txt)
[LFOB Geo.txt](https://github.com/vaccfr/France-Ground-Layouts/files/7163887/LFOB.Geo.txt)
[LFOB Labels.txt](https://github.com/vaccfr/France-Ground-Layouts/files/7163888/LFOB.Labels.txt)

**Comment by pierr3** [comment]
Implemented in November AIRAC
