### ISSUE TITLE
[Ajout secteur] LFLL

### ISSUE THREAD

**Issue by rmaure06** [vaccfr/France-Ground-Layouts#62]
Plateforme: LFLL
Pull request associé: #61 

Changelog: 
- Complete new AVISO for LFLL
- Matches new design standards
- Includes intermediates, CAT I and III holding points
- Includes red and orange taxi-lines as paths
- Includes gates as path

Fichiers format SCT:
[LFLL SCT - Maj.txt](https://github.com/vaccfr/France-Ground-Layouts/files/7197409/LFLL.SCT.-.Maj.txt)
[LFLL ESE - Maj.txt](https://github.com/vaccfr/France-Ground-Layouts/files/7197410/LFLL.ESE.-.Maj.txt)

Fichiers format GNG:
[LFLL Regions.txt](https://github.com/vaccfr/France-Ground-Layouts/files/7197418/LFLL.Regions.txt)
[LFLL Geo.txt](https://github.com/vaccfr/France-Ground-Layouts/files/7197419/LFLL.Geo.txt)
[LFLL Labels.txt](https://github.com/vaccfr/France-Ground-Layouts/files/7197420/LFLL.Labels.txt)

**Comment by pierr3** [comment]
Implemented in AIRAC 2111/01
