### ISSUE TITLE
[Ajout secteur] LFBO

### ISSUE THREAD

**Issue by rmaure06** [vaccfr/France-Ground-Layouts#68]
Plateforme: LFBO
Pull request associé: #69 

Changelog:
- Completely redrawn from scratch
- Updated freetext

Fichiers format GNG:
[LFBO Regions.txt](https://github.com/vaccfr/France-Ground-Layouts/files/8016335/LFBO.Regions.txt)
[LFBO Geo.txt](https://github.com/vaccfr/France-Ground-Layouts/files/8016336/LFBO.Geo.txt)
[LFBO Labels.txt](https://github.com/vaccfr/France-Ground-Layouts/files/8016337/LFBO.Labels.txt)

Fichiers format SCT:

[LFBO SCT - Maj.txt](https://github.com/vaccfr/France-Ground-Layouts/files/8016355/LFBO.SCT.-.Maj.txt)
[LFBO ESE - Maj.txt](https://github.com/vaccfr/France-Ground-Layouts/files/8016356/LFBO.ESE.-.Maj.txt)

**Comment by pierr3** [comment]
Implemented with AIRAc 2202/01
