### ISSUE TITLE
Retrieve good color code for groud Layout from currect LFPG layout in .sct file.

### ISSUE THREAD

**Issue by fx182ch** [vaccfr/France-Ground-Layouts#7]
And then update docs / wiki and files with it.

**Comment by rmaure06** [comment]
i updated the readme in my last pull request with what i think is the correct color code, at least it is the code i found when searching around the sector file

**Comment by rmaure06** [comment]
Done and merged, readme is now updated

**Comment by rmaure06** [comment]
Issue can be closed
