### ISSUE TITLE
[Ajout secteur] LFQQ

### ISSUE THREAD

**Issue by rmaure06** [vaccfr/France-Ground-Layouts#70]
Plateforme: LFQQ
Pull request associé: [TBD]

Changelog: 
- Completely redrawn from scratch
- Updated freetext

Fichiers format GNG:
[LFQQ Regions.txt](https://github.com/vaccfr/France-Ground-Layouts/files/8016376/LFQQ.Regions.txt)
[LFQQ Geo.txt](https://github.com/vaccfr/France-Ground-Layouts/files/8016377/LFQQ.Geo.txt)
[LFQQ Labels.txt](https://github.com/vaccfr/France-Ground-Layouts/files/8016375/LFQQ.Labels.txt)

Fichiers format SCT:
[LFQQ SCT - Maj.txt](https://github.com/vaccfr/France-Ground-Layouts/files/8016388/LFQQ.SCT.-.Maj.txt)
[LFQQ ESE - Maj.txt](https://github.com/vaccfr/France-Ground-Layouts/files/8016389/LFQQ.ESE.-.Maj.txt)

**Comment by pierr3** [comment]
Implemented in Airac 2202/02
