### ISSUE TITLE
[Ajout secteur] LFPN

### ISSUE THREAD

**Issue by rmaure06** [vaccfr/France-Ground-Layouts#75]
Plateforme: LFPN
Pull request associé: #74 

Changelog: 
- Complete new AVISO
- Added freetext for taxiways/parkings
- **Updated VRPs around LFPN**

Fichiers format GNG:
[LFPN Regions.txt](https://github.com/vaccfr/France-Ground-Layouts/files/8026523/LFPN.Regions.txt)
[LFPN Geo.txt](https://github.com/vaccfr/France-Ground-Layouts/files/8026524/LFPN.Geo.txt)
[LFPN Labels.txt](https://github.com/vaccfr/France-Ground-Layouts/files/8026525/LFPN.Labels.txt)
[LFPN Points VFR.txt](https://github.com/vaccfr/France-Ground-Layouts/files/8026526/LFPN.Points.VFR.txt)

Fichiers format SCT:
[LFPN SCT - Maj.txt](https://github.com/vaccfr/France-Ground-Layouts/files/8026529/LFPN.SCT.-.Maj.txt)
[LFPN ESE - Maj.txt](https://github.com/vaccfr/France-Ground-Layouts/files/8026530/LFPN.ESE.-.Maj.txt)
[LFPN ESE Points VFR - Maj.txt](https://github.com/vaccfr/France-Ground-Layouts/files/8026531/LFPN.ESE.Points.VFR.-.Maj.txt)

**Comment by pierr3** [comment]
Implemented with AIRAC 2202/01
