### ISSUE TITLE
[Ajout secteur] LFOA

### ISSUE THREAD

**Issue by rmaure06** [vaccfr/France-Ground-Layouts#77]
Plateforme: LFOA
Pull request associé: #76 

Changelog:
- Dessiné à l'aide des images satellites de 07/2015
- Création de freetext taxiways/parkings
- **Création de freetext points VFR**

Fichiers format GNG:
[LFOA Regions.txt](https://github.com/vaccfr/France-Ground-Layouts/files/8035395/LFOA.Regions.txt)
[LFOA Labels.txt](https://github.com/vaccfr/France-Ground-Layouts/files/8035396/LFOA.Labels.txt)
[LFOA Points VFR.txt](https://github.com/vaccfr/France-Ground-Layouts/files/8035397/LFOA.Points.VFR.txt)

Fichiers format SCT:
[LFOA SCT - Maj.txt](https://github.com/vaccfr/France-Ground-Layouts/files/8035399/LFOA.SCT.-.Maj.txt)
[LFOA ESE - Maj.txt](https://github.com/vaccfr/France-Ground-Layouts/files/8035400/LFOA.ESE.-.Maj.txt)
[LFOA ESE - Points VFR.txt](https://github.com/vaccfr/France-Ground-Layouts/files/8035401/LFOA.ESE.-.Points.VFR.txt)

**Comment by pierr3** [comment]
Implemented in AIRAC 2202/01
